### ISSUE TITLE
[FEAT] 시작화면 개발

### ISSUE THREAD

**Issue by Keun04** [pknu-wap/Dokdo_Public#1]
### 🏝️Issue
> 처음 웹에 들어왔을 때의 화면 개발

### 📆 Development Period
2024.10.02~2024.10.04

### 🖥️ Todo
- [x] 게임 로고 화면 정중앙 상단에 띄우기 (2024.10.02)
- [x] 시작 버튼 로고 밑에 구현 (2024.10.02)
- [x] 시작 버튼 클릭 시 닉네임 입력 모달창 구현 (2024.10.03)

### 🧩 Etc.
 > 기타사항 (참고할 만한 자료, 참고했던 자료, 궁금한 점 등)
