### ISSUE TITLE
[FEAT] Stage3 사진 팝업 제작 

### ISSUE THREAD

**Issue by khw010419** [pknu-wap/Dokdo_Public#12]
### 🏝️Issue
> 

### 📆 Development Period
> 10/11

### 🖥️ Todo
- [x] STAGE3의 벽에 임의의 사진 넣기(전체합쳐진 사진) (10/10)
- [x] 사진을 눌렀을 때 팝업 뜨게 하기 (10/10)
- [x] 팝업안에 사진 구현 (10/10)
- [x] 디자인 받은거 반영(10/12)
- [x] 모달창 수정(10/12)
- [x] 오답/정답 구현(10/12)
- [x] 쪽지 구현(10/12)

### 🧩 Etc.(선택)
 > 기타사항 (참고할 만한 자료, 참고했던 자료, 궁금한 점 등)
