### ISSUE TITLE
[DESIGN] 시작 페이지, 모달창, Toolbar 디자인 적용

### ISSUE THREAD

**Issue by Keun04** [pknu-wap/Dokdo_Public#15]
### 🖌️Design Overview
> 시작 페이지 로고, 시작버튼 수정
> 모달창 디자인 적용
> Toolbar 디자인 적용

### 🎯 Objective
> 디자인 나온 대로 적용

### 📆 Design Period
> 2024.10.12

### 🔮 Todo
- [x] 시작 페이지 로고, 버튼 수정 (2024.10.12)
- [x] 모달창 디자인 적용 (2024.10.12)
- [x] Toolbar 디자인 적용 (2024.10.12)

### 🧩 Etc
![시작_화면](https://github.com/user-attachments/assets/94f6ad47-6d7c-4b61-87f4-790257706b48)
> 시작 화면

![닉네임 모달창](https://github.com/user-attachments/assets/9b75681e-8cb8-4362-bbef-3c4c3e08798f)
> 모달창

![툴바](https://github.com/user-attachments/assets/5b62b216-9e6a-4dae-8d89-1bdb9d9b5d5a)
> 툴바
