### ISSUE TITLE
[FEAT] 인벤토리 구현

### ISSUE THREAD

**Issue by Keun04** [pknu-wap/Dokdo_Public#19]
### 🏝️Issue
> 인벤토리 창 구현

### 📆 Development Period
> 2024.10.14~2024.10.20

### 🖥️ Todo
- [x] 인벤토리 레이아웃 구성 및 디자인 적용 (2024.10.16)
- [x] Sortable 라이브러리 사용 (2024.10.16)
- [x] 아이템 클릭 시 인벤토리로 저장 (2024.10.17 ~ 2024.10.20)
- [x] 인벤토리 순서변경 저장 (2024.10.17 ~ 2024.10.20)

### 🧩 Etc.(선택)
 > 기타사항 (참고할 만한 자료, 참고했던 자료, 궁금한 점 등)
