### ISSUE TITLE
[FEAT] Stage1 오브젝트 확대 및 아이템 확대

### ISSUE THREAD

**Issue by Keun04** [pknu-wap/Dokdo_Public#21]
### 🏝️Issue
> Stage1 오브젝트 확대

### 📆 Development Period
> 2024.10.22~2024.10.24

### 🖥️ Todo
- [x] 악보 클릭 시 확대 (2024.10.22)
- [x] 인벤토리 아이템 클릭 시 확대 구현 (2024.10.22)
- [x] 인벤토리 아이템 확대 시 스크롤 막기 (2024.10.24)
- [x] 오브젝트 vh, vw로 재조정 (2024.10.24)
- [x] 해상도 변경 시 깨짐 현상 해결

![image](https://github.com/user-attachments/assets/6c37394d-4032-4e56-ac55-22a8bce453ad)
> 갑자기 악보 확대 화면이 내려감 해결하기

오브젝트 확대 백그라운드 position을 relative에서 fixed로 바꾸고 top:0 하니까 해결

![image](https://github.com/user-attachments/assets/d6f26636-6ac9-4376-96c0-92059b09b63d)
> 인벤토리 아이템 확대 시 서랍이 사라짐.. 해결하기

Drawer를 div로 감싸니까 갑자기 잘 나옴. 이유를 모르겠음

### 🧩 Etc.(선택)
 > 기타사항 (참고할 만한 자료, 참고했던 자료, 궁금한 점 등)
