### ISSUE TITLE
[FEAT] mustache 아이템 기능

### ISSUE THREAD

**Issue by suhyun113** [pknu-wap/Dokdo_Public#29]
### 🏝️Issue
> 아이템 추가 및 삭제 기능 HTML 화면 구현(임시)
> 배포한 것을 보여주기 위함

### 📆 Development Period
> 2024.10.29 ~ 2024.10.30

### 🖥️ Todo
- [x] Mustache에 맞게 컨트롤러 파일 수정(10.29)
- [x] inventoryForm.mustache 파일 구현(10.30)
- [x] inventoryItems.mustache 파일 구현(10.30)

> 디자인 추가
- [x] 아이템 추가 및 삭제 폼 페이지 디자인 추가(10.30)
- [x] 인벤토리 ID별 아이템 목록 페이지 디자인 추가(10.30)

### 🧩 Etc.(선택)
 > 기타사항 (참고할 만한 자료, 참고했던 자료, 궁금한 점 등)
