### ISSUE TITLE
[DESIGN] Stage2, Stage3, 인벤토리 UI 수정

### ISSUE THREAD

**Issue by Keun04** [pknu-wap/Dokdo_Public#38]
### 🖌️Design Overview
> 전체적인 UI 깨짐 수정

### 🎯 Objective
> 화면 안깨지도록 전체적인 단위 수정

### 📆 Design Period
> 2024.10.30~2024.11.03

### 🔮 Todo
- [x] 인트로 폰트 크기 수정 (2024.10.30)
- [ ] Stage2 깨짐 수정
- [ ] Stage3 깨짐 수정
- [ ] 인벤토리 아이템 크기 깨짐 수정

### 🧩 Etc.(선택)
 > 기타사항 (피그마, 스케치 등의 시안 자료)
