### ISSUE TITLE
[FEAT] Stage3 사진 확대 구현

### ISSUE THREAD

**Issue by khw010419** [pknu-wap/Dokdo_Public#4]
### 🏝️Issue
> Room3에서 진행되는 2개의 스테이지 구현

### 📆 Development Period
> 2024.10.4
ex) 2024.09.30~2024.10.02

### 🖥️ Todo
- [x] Room3 스테이지1 벽에 사진 넣기
- [x] Room3 스테이지1 벽에 있는 사진 클릭시 확대, 클릭시 줄어들게 구현하기 
- [x] Room3 스테이지1 선택된 사진을 보여주는 모달창 구현 ➡️ 우리 팀 공통 코드로 수정필요함!

*구현 완료 후, 체크 박스 체크하고 오른쪽에 완료 날짜 작성 가능
ex) [x] 구현 내용1(2024.09.30)

### 🧩 Etc.(선택)
 > 기타사항 (참고할 만한 자료, 참고했던 자료, 궁금한 점 등)

**Comment by khw010419** [comment]
- 임의의 사진으로 코드구현만 해봄
- 다른 프론트 개발자가 작성한 모달코드로 변경해야함

![스크린샷(30)](https://github.com/user-attachments/assets/47f26284-71d1-406e-9d73-4694a627d0dd)
➡️Room3의 벽에는 여러 사진이 있고, 사진을 클릭했을 때 사진이 확대되는 기능을 구현해야함

![스크린샷(31)](https://github.com/user-attachments/assets/958ef6ec-a5c9-4b76-8c2e-54574719607e)
➡️사진을 누르면 확대됨

![스크린샷(32)](https://github.com/user-attachments/assets/b7c145fc-c8d3-4fc9-bde6-babeb0dc0770)
➡️사진이 확대된 상태에서만 정답을 맞출 수 있는 팝업(모달)을 띄울 수 있는 '버튼'이 보임

![스크린샷(32)](https://github.com/user-attachments/assets/7c7f82fd-114b-445c-82aa-b38d5a41b1bb)
➡️해당 버튼을 누르면 누른 사진이 뜨는 모달창이 열림. 
➡️우리는 총 3개의 사진이 들어가야 함 하지만 일단 1개씩 들어가게 구현함

![스크린샷(33)](https://github.com/user-attachments/assets/37f2d268-1506-47e9-b8c6-459884f5fdac)
➡️태극기를 눌렀을 때 모달창에는 일본국기 대신 태극기의 사진으로 바뀜

**Comment by khw010419** [comment]
수정
