### ISSUE TITLE
[FEAT] News, Stage1 마무리 및 백엔드 연결

### ISSUE THREAD

**Issue by Keun04** [pknu-wap/Dokdo_Public#43]
### 🏝️Issue
> Session Storage로 프론트에서 저장했던 코드를 백엔드 주소로 변경

### 📆 Development Period
> 2024.11.04~2024.11.19

### 🖥️ Todo
- [x] SESSION ID 받아오기 (2024.11.06~2024.11.14)
- [x] Stage1 쪽지 띄우기 및 세션 연결 (2024.11.14)
- [x] 뉴스 화면 마무리 (2024.11.04) -> 일단 슬라이드 형식으로 해 둠
- [x] Inventory 백엔드 연결 (2024.11.14)
- [x] Stage 백엔드 연결 (2024.11.16)
- [x] Session 사용자 POST (2024.11.04~2024.11.07)
- [x] 아이템 Delete 함수 생성

### 🧩 Etc.(선택)
 > 기타사항 (참고할 만한 자료, 참고했던 자료, 궁금한 점 등)
