### ISSUE TITLE
[FEAT] 스테이지4 진행 상황 기능

### ISSUE THREAD

**Issue by suhyun113** [pknu-wap/Dokdo_Public#49]
### 🏝️Issue
> 스테이지4에서 주어지는 미션별 하트를 관리하여 생명 시스템을 구현하고자 하였습니다. 미션 성공 시 다음 미션으로 이동하고, 하트 모두 소진 시, 게임을 처음부터 다시 시작하게 설정합니다.

**구현할 기능**
`POST /stage/4/mission/start` : 초기화(시작) 기능
`POST /stage/4/mission/attempt `: 미션 도전 기능
`GET /stage/4/status` : 상태 조회 기능
`POST /stage/4/mission/retry` : 미션 재도전 기능
`POST /stage/4/reset` : 초기화(게임 오버) 기능
'POST /stage/4/puzzle/result' : 퍼즐 게임 결과 처리

### 📆 Development Period
> 2024.11.14 ~ 2024.11.18 (19일 회의 전까지)
> 2024.11.18 ~ 2024.11.22 

### 🖥️ Todo
- [x] Stage4Progress DB 추가(2024.11.14)
- [x] Stage4Progress Entity(2024.11.15)
- [x] Stage4Progress Repository(2024.11.15)
- [x] Stage4Progress Dto(2024.11.16)

> 각 기능별 Service 구현
- [x] 각 기능별 Service 로직 작성(2024.11.16)
- [x] 미션 재도전 기능(2024.11.17)
- [x] 초기화(게임 오버) 기능(2024.11.17)
- [x] 퍼즐 게임 결과 처리 기능(2024.11.19) 

> 각 기능별 Controller 구현
- [x] 미션 재도전 기능(2024.11.17)
- [x] 초기화(게임 오버) 기능(2024.11.17)
- [x] 퍼즐 게임 결과 처리 기능(2024.11.19)

> API 테스트(포스트맨, 스웨거)
- [x] 미션 재도전 기능(2024.11.18)
- [x] 초기화(게임 오버) 기능(2024.11.18)
- [x] 퍼즐 게임 결과 처리 기능(2024.11.19)

> 기능 수정
- 미션 재도전 기능 삭제
- 초기화(게임 오버) 기능 + 퍼즐 게임 결과 처리 기능
- [x] 초기화 기능(2024.11.26)

### 🧩 Etc.(선택)
 > 기타사항 (참고할 만한 자료, 참고했던 자료, 궁금한 점 등)
