### ISSUE TITLE
[FEAT] Stage2 지도 암호 구현

### ISSUE THREAD

**Issue by aranlll** [pknu-wap/Dokdo_Public#5]
### 🏝️Issue
> 지도 암호 구현

### 📆 Development Period
> 2024.10.02-

### 🖥️ Todo
- [x] 상자 열리는 기능 구현
- [x] 지도가 있는 책장 구현
- [x] 책장 애니메이션 구현
- [x] 지도 줍기 기능 구현

*구현 완료 후, 체크 박스 체크하고 오른쪽에 완료 날짜 작성 가능
ex) [x] 구현 내용1(2024.09.30)

### 🧩 Etc.(선택)
 > 기타사항 (참고할 만한 자료, 참고했던 자료, 궁금한 점 등)
