### ISSUE TITLE
[FEAT] Stage4 Room1,2,3 구현

### ISSUE THREAD

**Issue by khw010419** [pknu-wap/Dokdo_Public#53]
### 🏝️Issue
> stage3 디자인 반영 및 css수정, stage4의 room1~3 구현

### 📆 Development Period
> ~2024.11.18

### 🖥️ Todo
- [x] stage3 디자인 반영 
- [x] stage3 css수정
- [x] stage room1 
- [x] stage room2
- [x] stage room3
- [x] gameover 구현
- [x] 숫자모달 글자 중앙으로 배치
- [x] 총힌트 사진 수정
- [x] stage3, stage4 css vh위주로 수정 -> 바닥사이즈와 문사이즈의 변환되는 비율 수정
- [x] stage4사람 css 수정
- [x] stage3,4 임시 지도 퍼즐 넣기
- [x] 홈으로가기.. 으로 변경하기 (네비게이션도 수정)
- [x] stage4에서 사람을 사람한테 드래그기능막기
