### ISSUE TITLE
[FEAT] Stage4 백엔드 연동

### ISSUE THREAD

**Issue by Keun04** [pknu-wap/Dokdo_Public#61]
### 🏝️Issue
> Stage4 백엔드 연동

### 📆 Development Period
> 2024.11.23~2024.11.24

### 🖥️ Todo
- [ ] Stage4 UserContext 연결
- [ ] Room1,2,3 미션 백엔드 연도
- [ ] 하트 백엔드 연동

### 🧩 Etc.(선택)
 > 기타사항 (참고할 만한 자료, 참고했던 자료, 궁금한 점 등)
