### ISSUE TITLE
[FEAT] stage3, stage4 오류수정

### ISSUE THREAD

**Issue by khw010419** [pknu-wap/Dokdo_Public#62]
### 🏝️Issue
> stage3 오류수정

### 📆 Development Period
> 11/23~11/24

### 🖥️ Todo
- [x] 아이템 먹고 다른 스테이지 갔다왔을 때 저장되어 있게 해야함
- [x] 그 상태에서 문 클릭했을 때도 모달창 뜨도록 구현
- [x] 독도퍼즐 수집했는데도 계속뜨는 문제 해결

**Comment by khw010419** [comment]
굿
