### ISSUE TITLE
[FEAT] Final

### ISSUE THREAD

**Issue by khw010419** [pknu-wap/Dokdo_Public#74]
### 🏝️Issue
> stage3, stage4 최종수정

### 📆 Development Period
> 2024.11.28

### 🖥️ Todo
- [x] 친일파 정보힌트 화면에 보인 후 인벤토리에 담기기
- [x] 필요없는 코드 제거
- [x] 사진변경
- [x] gameover을 컴포넌트에서 pages로 옮김

**Comment by khw010419** [comment]
굿
